name: wolke7-connector CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Upload build artifact
      uses: actions/upload-artifact@v1
      with:
        name: wolke7-connector-artifact
        path: build/libs/wolke7-connector-0.0.1-SNAPSHOT.jar

  build_and_push_docker_image:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v1
      - name: Download artifact from cache
        uses: actions/download-artifact@v1
        with:
          name: wolke7-connector-artifact
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          login-server: docker.pkg.github.com
          username: $GITHUB_ACTOR
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag docker.pkg.github.com/nepomuk-software/wolke7-connector/wolke7-connector:$(git rev-parse --short HEAD)
      - name: Push the Docker image
        run: docker push docker.pkg.github.com/nepomuk-software/wolke7-connector/wolke7-connector
      - name: Paste new Docker image to deployment definition
        run: sed -ie "s/IMAGE_TAG/$(git rev-parse --short HEAD)/g" deployment.yml
      - name: Create Deployment
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.kubeconfig }}
          args: apply -f deployment.yml
      - name: Create Service
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.kubeconfig }}
          args: apply -f service.yml
      - name: Create Ingress
        uses: nickgronow/kubectl@master
        with:
          config_data: ${{ secrets.kubeconfig }}
          args: apply -f ingress.yml